name: CD-Prod Pipeline

permissions:
  actions: read
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy-prod
    runs-on: ubuntu-latest
    environment:
      name: production  # Für manuelles Approval im Environments

    steps:

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Pull Docker image (latest-tested)
      run: |
        docker pull ghcr.io/${{ github.repository }}/myapp:latest-tested

    - name: Read embedded commit SHA label (for logs/audit)
      run: |
        IMG=ghcr.io/${{ github.repository }}/myapp:latest-tested
        REV=$(docker inspect -f '{{ index .Config.Labels "org.opencontainers.image.revision" }}' $IMG)
        echo "Deploying image built from commit: $REV"

    - name: Start prod container (smoke test)
      run: |
        docker run -d --name prod-app -p 80:80 ghcr.io/${{ github.repository }}/myapp:latest-tested

    - name: Verify container is running
      run: |
        set -e
        # wait up to ~30s for running state
        for i in {1..15}; do
          if docker ps --filter "name=prod-app" --filter "status=running" --format '{{.Names}}' | grep -q '^prod-app$'; then
            echo "Container is running"
            exit 0
          fi
          sleep 2
        done
        echo "Container did not reach running state in time" >&2
        exit 1

    - name: Promote image to prod-current
      if: ${{ success() }}
      run: |
        set -e
        SRC=ghcr.io/${{ github.repository }}/myapp:latest-tested
        TGT=ghcr.io/${{ github.repository }}/myapp:prod-current
        docker tag "$SRC" "$TGT"
        docker push "$TGT"

    - name: Stop and remove prod container
      if: always()
      run: docker rm -f prod-app || true
