name: CD-Prod Pipeline

permissions:
  actions: read
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy-prod
    runs-on: ubuntu-latest
    environment:
      name: production  # sorgt für manuelles Approval
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Pull Docker image
      run: |
        echo "Pulling image with SHA: ${{ github.sha }}"
        docker pull ghcr.io/${{ github.repository }}/myapp:${{ github.sha }}

    - name: Deploy Application
      run: |
        docker run -d -p 80:80 ghcr.io/${{ github.repository }}/myapp:${{ github.sha }}
