name: CD-Prod Pipeline

permissions:
  actions: read
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy-prod
    runs-on: ubuntu-latest
    environment:
      name: production  # Für manuelles Approval im Environments-Tab

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Voller Git-Verlauf, um Tags abzufragen

    - name: Get commit SHA behind latest-tested tag
      id: get_sha
      run: |
        GIT_SHA=$(git rev-parse latest-tested)
        echo "GIT_SHA=$GIT_SHA" >> $GITHUB_ENV
        echo "Commit SHA from latest-tested tag: $GIT_SHA"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Pull Docker image
      run: |
        echo "Pulling image with SHA: ${{ env.GIT_SHA }}"
        docker pull ghcr.io/${{ github.repository }}/myapp:${{ env.GIT_SHA }}

    - name: Deploy Application
      run: |
        docker run -d -p 80:80 ghcr.io/${{ github.repository }}/myapp:${{ env.GIT_SHA }}
