name: CD-Prod Pipeline

permissions:
  actions: read
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy-prod
    runs-on: ubuntu-latest
    environment:
      name: production  # Für manuelles Approval im Environments

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Voller Git-Verlauf, um Tags abzufragen

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Pull Docker image (latest-tested)
      run: |
        docker pull ghcr.io/${{ github.repository }}/myapp:latest-tested

    - name: Read embedded commit SHA label (for logs/audit)
      run: |
        IMG=ghcr.io/${{ github.repository }}/myapp:latest-tested
        REV=$(docker inspect -f '{{ index .Config.Labels "org.opencontainers.image.revision" }}' $IMG)
        echo "Deploying image built from commit: $REV"

    - name: Deploy Application
      run: |
        docker run -d -p 80:80 ghcr.io/${{ github.repository }}/myapp:latest-tested
