name: CD-Prod Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: your-username
        minimum-approvals: 1
        issue-title: "Approval needed for deployment to production"
        issue-body: "Please approve or deny the deployment to production."

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    environment:
        name: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Pull Docker image
      run: |
        docker pull ghcr.io/${{ github.repository }}/myapp:latest

    - name: Deploy Application
      run: |
        docker run -d -p 80:80 ghcr.io/${{ github.repository }}/myapp:latest