name: CD-Prod Pipeline

permissions:
  actions: read
  contents: read

on:
  workflow_run:
    workflows: ["CD-Test Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Get Git SHA from CD-Test workflow (Test)
      id: get_sha
      run: |
        # Get the commit SHA from the workflow run that triggered this
        GIT_SHA=$(echo "${{ github.event.workflow_run.head_sha }}" | cut -c1-7)
        echo "GIT_SHA=${GIT_SHA}" >> $GITHUB_ENV
        echo "Using Git SHA from CD-Test: ${GIT_SHA}"

    - name: Pull Docker image
      run: |
        echo "Pulling image with SHA: ${{ env.GIT_SHA }}"
        docker pull ghcr.io/${{ github.repository }}/myapp:${{ env.GIT_SHA }}

    - name: Deploy Application
      run: |
        docker run -d -p 80:80 ghcr.io/${{ github.repository }}/myapp:${{ env.GIT_SHA }}
