name: CD-Test Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Get Git SHA
      id: git_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build Docker image for Linux
      run: |
        docker buildx build --platform linux/amd64 -t myapp:latest . --load

    - name: Tag Docker image
      run: |
        docker tag myapp:latest ghcr.io/${{ github.repository }}/myapp:${{ steps.git_sha.outputs.sha }}

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/myapp:${{ steps.git_sha.outputs.sha }}