name: CD-Test Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Wichtig: vollständiger Git-Verlauf, um Tags pushen zu können

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build Docker image for Linux
      run: |
        docker buildx build --platform linux/amd64 -t myapp:latest . --load

    - name: Tag Docker image with commit SHA
      run: |
        echo "Tagging image with SHA: ${{ github.sha }}"
        docker tag myapp:latest ghcr.io/${{ github.repository }}/myapp:${{ github.sha }}

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/myapp:${{ github.sha }}

    - name: Create or update 'latest-tested' tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configure git user
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Create or update lightweight tag 'latest-tested' pointing to current commit
        git tag -f latest-tested ${{ github.sha }}

        # Push tag to remote
        git push origin --force --tags
