name: Debug Workflow Run

on:
  workflow_run:
    workflows: ["CD-Test Pipeline"]
    types:
      - completed

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug workflow run event
      run: |
        echo "=== Workflow Run Debug ==="
        echo "Workflow run triggered!"
        echo "Event: ${{ github.event_name }}"
        echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
        echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
        echo "Workflow ID: ${{ github.event.workflow_run.id }}"
        echo "Workflow name: ${{ github.event.workflow_run.name }}"
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "=== End Debug ===" 